name: Broken station
description: Report a broken radio station
title: 'Broken: '
labels: ['streams:broken']

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the issue template as much as you can so we could efficiently process your request.

  - type: input
    attributes:
      label: Concerned radio station (required)
      description: Please specify the broken radio station
      placeholder: 'https://example.com/playlist.m3u8 | https://example.com/stream.aac [Recommended] | https://example.com/stream.mp3'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: What happened to the radio station ?
      options:
        - Not loading
        - Constantly interrupts/lagging
        - No sound
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes (optional)
      placeholder: 'If Other was chosen, please specify what happened.'
